### ISSUE TITLE
Is it possible to specify the cloud-init config data directly inline?

### ISSUE THREAD

**Issue by nickbroon** [stafwag/ansible-role-cloud_localds#1]
Should it be possible to specify the cloud-init config data directly inline?
ie, something like this:

```
cloud_localds:
  dest: '/var/lib/libvirt/images/ci-data.iso'
  overwrite: True
  owner: libvirt-qemu
  group: libvirt-qemu
  mode: 644
  config:
    network:
      version: 2
      ethernets:
        ens2:
          addresses:
            - 10.0.2.2/24
          gateway4: 10.0.2.1
          nameservers:
            addresses: [10.0.2.1]
    users:
      - default
      - name: user1
      - groups: sudo
      - ssh_authorized_keys:
        - ssh-rsa blahblahblah
```

Or is it required to be a string (or lookup file/template)?
